---
- name: Enable HTTPS incoming traffic
  hosts: oci
  become: true
  gather_facts: false

  # Note order of the rules is important. Rules need to be added in sequence and before first REJECT or DROP rule.
  # Default image INPUT chain has a REJECT rule at position 5.
  tasks:
    - name: Configure INPUT firewall rules
      ansible.builtin.iptables:
        chain: INPUT
        action: insert
        rule_num: "{{ item.rule_num }}"
        protocol: "{{ item.protocol }}"
        destination_port: "{{ item.destination_port }}"
        jump: ACCEPT
        match: "{{ item.match | default(omit) }}"
        ctstate: "{{ item.ctstate | default(omit) }}"
        comment: "{{ item.comment }}"
        state: "{{ ip_tables_state }}"
      loop: "{{ input_rules + (additional_input_rules | default([])) }}"

    - name: Save current state of the firewall in system file
      community.general.iptables_state:
        ip_version: ipv4
        table: filter
        state: saved
        path: /etc/iptables/rules.v4